const constant = {
    SET_DATA_TO_SELECT: "SET_DATA_TO_SELECT",
    SET_BOOK_TO_EDIT: "SET_BOOK_TO_EDIT",
    SET_GENRE_TO_EDIT: "SET_GENRE_TO_EDIT",
    SET_AUTHOR_TO_EDIT: "SET_AUTHOR_TO_EDIT",
    CREATE_NEW_GENRE: "CREATE_NEW_GENRE",
    CREATE_NEW_AUTHOR: "CREATE_NEW_AUTHOR",
    CREATE_NEW_BOOK: "CREATE_NEW_BOOK",
    BOOK_EDIT: "BOOK_EDIT",
    GENRE_EDIT:"GENRE_EDIT",
    AUTHOR_EDIT:"AUTHOR_EDIT",
    SET_VALUE: "SET_VALUE",
    CLOSE_FORM: "CLOSE_FORM"
};

export default constant;